version: "3"

services:
  postgresql:
    build:
      context: ./postgre
      args:
        TARGET_ROADS: wojewodztwa/wojewodztwa.shp
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: geotronics
    ports:
      - "5432:5432"
    # volumes:
    # - D:/Programming/DockerData/MssqlVolume:/my/sql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  app:
    build: ./src
    ports:
      - "5192:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: Host=postgresql;Username=postgres;Password=123456;Database=geotronics;
    depends_on:
      postgresql:
        condition: service_healthy
